Update signals.py
kfdm/django-mqtt pull request #6
Opened 2024-12-30 04:06 UTC by leosok

fix: replace mqtt wildcard # with * in topic matcher

Replaces MQTT-style wildcard # with Unix-style * in topic matcher to make fnmatch work correctly with MQTT topics. This ensures proper topic matching functionality since fnmatch expects Unix-style wildcards.

2024-12-30 04:09 UTC, leosok commented
took me a while to realize what was going wrong. I found it much better to 
`@topic(foo/#)` than to  use `@topic(foo/*)` , which is how to use it right now.

2025-01-06 06:08 UTC, kfdm commented
Ah, that's a good catch! I likely should write a few test cases around there to catch things like this better.

2025-01-06 15:18 UTC, leosok commented
In the meantime I found out that there is also a '+' as an option, like "foo/+/bar" which will match exactly one string. Wrote some code to accommodate this too.

2025-01-16 09:06 UTC, kfdm requested changes
All of this generally looks great! I need to look at the convert_wildcards a bit more closely to make sure I understand the logic but at first glance it seems reasonable.

Seems like I had done a lot more changes locally but hadn't pushed them to github, so may require a bit of rebasing on your end. I tried to use the github suggest commit here, and could fix it myself, but wanted to give you the option to fix it to ensure you remain credited in the commits themselves.

2025-01-16 09:06 UTC, kfdm commented on dmqtt/signals.py
> +    return '^' + pattern + '$'
```suggestion
def convert_wildcards(mqtt_topic) -> re.Pattern:
    """Convert MQTT wildcards to regex pattern.
    '#' becomes '.*' (multi-level)
    '+' becomes '[^/]+' (single-level)
    """
    pattern = re.escape(mqtt_topic)
    pattern = pattern.replace("\\#", ".*")
    pattern = pattern.replace("\\+", "[^/]+")
    return re.compile(f"^{pattern}$")
```

We can do the compiling of the pattern here once, and return it as a small optimization.

2025-01-16 09:06 UTC, kfdm commented on dmqtt/signals.py
>          def inner(msg, **kwargs):
```suggestion
def topic(matcher, as_json=True, **extras):
    regex_pattern = convert_wildcards(matcher)

    def wrap(func):
        @functools.wraps(func)
        def inner(msg, **kwargs):
```

For the same reason, we move the regex pattern here so that it's converted and compiled a single time at startup.

2025-01-16 09:06 UTC, kfdm commented on dmqtt/signals.py
> +                logger.debug("Matched %s for %s", regex_pattern, func)
```suggestion
            if regex_pattern.match(msg.topic):
                logger.debug("Matched %s for %s", regex_pattern, func)
```

Now this line uses our compiled matcher

2025-01-16 09:06 UTC, kfdm commented on tests/test_mqtt_wildcards.py
> +    assert not re.match(pattern, "home/status")
```suggestion
from dmqtt.signals import convert_wildcards


from . import BaseTest


class WildcardTest(BaseTest):
    def test_single_level_wildcard(self):
        pattern = convert_wildcards("home/+/status")
        assert pattern.match("home/kitchen/status")
        assert not pattern.match("home/kitchen/lights/status")

    def test_multi_level_wildcard(self):
        pattern = convert_wildcards("home/#")
        assert pattern.match("home/kitchen/status")
        assert pattern.match("home/kitchen/lights/status")

    def test_mixed_wildcards(self):
        pattern = convert_wildcards("home/+/lights/#")
        assert pattern.match("home/kitchen/lights/status")
        assert pattern.match("home/bathroom/lights/brightness/set")
        assert not pattern.match("home/status")
```

Need to update this to a model based test. Since convert_wildcards returns a regex, we fix it here as well.

2025-11-29 09:30 UTC, kfdm commented
Fixed in https://github.com/kfdm/django-mqtt/commit/28b435e679c123a35f728e6c56786d83a9ba72ac

2025-11-29 09:30 UTC, closed without merging